- id: '1684703376299'
  alias: Power on LG TV
  description: Power on the main living room TV
  trigger:
  - platform: device
    device_id: 9da212e6abf5c6272b4d5c9359565f3c
    domain: webostv
    type: webostv.turn_on
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: 20:17:42:72:DD:D9
  mode: single
- id: '1684955651080'
  alias: '[Notify] - Water leak'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_matan_s23
    data:
      message: Water leak at {{ trigger.name }}
      title: Wate leak
  - service: notify.mobile_app_hen_s23
    data:
      message: Water leak at {{ trigger.name }}
      title: Water leak
  mode: single
- id: '1685172148575'
  alias: '[Notify] - Storage door open'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.storage_door_contact
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_matan_s23
    data:
      message: Storage door is open
  - service: notify.mobile_app_hen_s23
    data:
      message: Storage door is open
    enabled: true
  mode: single
- id: '1685305554885'
  alias: '[Startup] - Apply default theme'
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: frontend.set_theme
    data:
      mode: dark
      name: noctis
  mode: single
- id: '1690735672187'
  alias: '[Motion] - Turn on bathroom light'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bathroom_motion_sensor_occupancy
    from: 'off'
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.bathroom_motion_sensor_illuminance_lux
    below: 90
  action:
  - type: turn_on
    device_id: 9700798447239bb9c80eb4fd137b5d23
    entity_id: da3b36ca0ef97d1533dcd552c5b054fd
    domain: switch
  mode: single
- id: '1690737637122'
  alias: '[Motion] Turn off bathroom light '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bathroom_motion_sensor_occupancy
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition: []
  action:
  - type: turn_off
    device_id: 9700798447239bb9c80eb4fd137b5d23
    entity_id: da3b36ca0ef97d1533dcd552c5b054fd
    domain: switch
  mode: single
- id: '1690898247747'
  alias: '[Motion] - Turn on parents bathroom LED'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.parents_bathroom_motion_sensor_occupancy
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - type: motion
    platform: device
    device_id: 8980b06e19a58d5623a2f86d18baa332
    entity_id: d55fe80f0fe3f7fb86436c54db089a6a
    domain: binary_sensor
  condition:
  - condition: time
    after: '20:00:00'
    enabled: true
    before: 06:00:00
  action:
  - type: turn_on
    device_id: 8d295f7e94d98f23db6c37d11166633d
    entity_id: ad4c403daa105bc6586da91267e7528d
    domain: light
    brightness_pct: 1
  mode: single
- id: '1692436824869'
  alias: '[Motion] - Turn off parents bathroom LED'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.parents_bathrom_presence_ld1125h_occupancy_or_movement
    from:
    to: 'off'
  condition: []
  action:
  - type: turn_off
    device_id: 8d295f7e94d98f23db6c37d11166633d
    entity_id: ad4c403daa105bc6586da91267e7528d
    domain: light
  mode: single
