- id: '1684703376299'
  alias: Power on LG TV
  description: Power on the main living room TV
  trigger:
  - platform: device
    device_id: 9da212e6abf5c6272b4d5c9359565f3c
    domain: webostv
    type: webostv.turn_on
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: 20:17:42:72:DD:D9
  mode: single
- id: '1684955651080'
  alias: Water leak notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_matans_iphone
    data:
      message: Water leak at {{ trigger.name }}
      title: Wate leak
  - service: notify.mobile_app_hen_s_galaxy
    data:
      message: Water leak at {{ trigger.name }}
      title: Water leak
      data:
        '[object Object]':
    enabled: true
  mode: single
- id: '1685172148575'
  alias: Storage door notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.storage_door_contact
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_matans_iphone
    data:
      message: Sotorage door is open
  - service: notify.mobile_app_hen_s_galaxy
    data:
      message: Storage door is open
  mode: single
- id: '1685305554885'
  alias: Apply default theme
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: frontend.set_theme
    data:
      mode: dark
      name: noctis
  mode: single
- id: '1690735672187'
  alias: Bathroom light - activate by motion
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bathroom_motion_sensor_occupancy
    from: 'off'
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.bathroom_motion_sensor_illuminance_lux
    below: 90
  action:
  - type: turn_on
    device_id: 9700798447239bb9c80eb4fd137b5d23
    entity_id: da3b36ca0ef97d1533dcd552c5b054fd
    domain: switch
  mode: single
- id: '1690737637122'
  alias: Bathroom light - turn off when no motion
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bathroom_motion_sensor_occupancy
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition: []
  action:
  - type: turn_off
    device_id: 9700798447239bb9c80eb4fd137b5d23
    entity_id: da3b36ca0ef97d1533dcd552c5b054fd
    domain: switch
  mode: single
- id: '1690898247747'
  alias: Parents bathroom switch - activate by motion
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.parents_bathroom_motion_sensor_occupancy
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 3
  condition:
  - condition: time
    after: '21:30:00'
    enabled: true
    before: 05:00:00
  action:
  - type: turn_on
    device_id: 400f69dff063dbf370f67c2c4abf2f76
    entity_id: d3f62b4de75a868e5f800b009e067805
    domain: light
  mode: single
