- id: '1684703376299'
  alias: Power on LG TV
  description: Power on the main living room TV
  trigger:
  - platform: device
    device_id: 9da212e6abf5c6272b4d5c9359565f3c
    domain: webostv
    type: webostv.turn_on
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: 20:17:42:72:DD:D9
  mode: single
- id: '1684955651080'
  alias: '[Notify] - Water leak'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_matan_s23
    data:
      message: Water leak at {{ trigger.name }}
      title: Wate leak
  - service: notify.mobile_app_hen_s23
    data:
      message: Water leak at {{ trigger.name }}
      title: Water leak
  mode: single
- id: '1685172148575'
  alias: '[Notify] - Storage door open'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.storage_door_contact
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_matan_s23
    data:
      message: Storage door is open
  - service: notify.mobile_app_hen_s23
    data:
      message: Storage door is open
    enabled: true
  mode: single
- id: '1685305554885'
  alias: '[Startup] - Apply default theme'
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: frontend.set_theme
    data:
      mode: dark
      name: noctis
  mode: single
- id: '1690898247747'
  alias: '[Motion] - Turn on parents bathroom LED'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.parents_bathroom_motion_sensor_occupancy
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - type: occupied
    platform: device
    device_id: 8980b06e19a58d5623a2f86d18baa332
    entity_id: cf40d72b78eb93ac41a1e5dc72083999
    domain: binary_sensor
  condition:
  - condition: sun
    before: sunrise
    after: sunset
    enabled: true
  action:
  - type: turn_on
    device_id: 8d295f7e94d98f23db6c37d11166633d
    entity_id: ad4c403daa105bc6586da91267e7528d
    domain: light
    brightness_pct: 1
  mode: single
- id: '1692436824869'
  alias: '[Motion] - Turn off parents bathroom LED'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.parents_bathrom_presence_ld1125h_occupancy_or_movement
    from: 'on'
    to: 'off'
  condition: []
  action:
  - type: turn_off
    device_id: 8d295f7e94d98f23db6c37d11166633d
    entity_id: ad4c403daa105bc6586da91267e7528d
    domain: light
  mode: single
- id: '1694193356542'
  alias: '[Motion] - Turn on bathroom light'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.main_bathroom_presence_ld1125h_occupancy_or_movement
    from:
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: sun
    before: sunrise
    after: sunset
    enabled: false
  action:
  - type: turn_on
    device_id: 9700798447239bb9c80eb4fd137b5d23
    entity_id: e1fd4c1a9793ee9a2abd9c58ffeb4d50
    domain: light
  mode: single
- id: '1694193434232'
  alias: '[Motion] - Turn off bathroom light'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.main_bathroom_presence_ld1125h_occupancy_or_movement
    from: 'on'
    to: 'off'
  condition: []
  action:
  - type: turn_off
    device_id: 9700798447239bb9c80eb4fd137b5d23
    entity_id: e1fd4c1a9793ee9a2abd9c58ffeb4d50
    domain: light
  - type: turn_off
    device_id: 9700798447239bb9c80eb4fd137b5d23
    entity_id: c236faa3c78205fefa7d0ec5a02fc29b
    domain: light
  mode: single
- id: '1696092829450'
  alias: '[Sunset] - turn on tv counter led'
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.wled_tv_counter
  mode: single
- id: '1696093001946'
  alias: '[Sunrise] - turn off tv counter led'
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.wled_tv_counter
  mode: single
- id: '1697396037927'
  alias: '[Time] - Turn off living room TV '
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  condition: []
  action:
  - type: turn_off
    device_id: 42b83ade3def14a661eec3d107164ba9
    entity_id: 7cd0d46b3df7f185433c1eab0b7e02d5
    domain: switch
  mode: single
- id: '1697396097180'
  alias: '[Time] - Turn on living room TV '
  description: ''
  trigger:
  - platform: time
    at: 08:30:00
  condition: []
  action:
  - type: turn_on
    device_id: 42b83ade3def14a661eec3d107164ba9
    entity_id: 7cd0d46b3df7f185433c1eab0b7e02d5
    domain: switch
  mode: single
